version: '3.8'
services:
  db:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m src.bot
    volumes:
      - ./:/app
    depends_on:
      - db
  broker:
    container_name: redis-server
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  tasks:
    container_name: celery_tasks
    build:
      context: .
      dockerfile: src/tasks/Dockerfile.celery
    depends_on:
      - broker
      - app
    command: celery -A src.tasks.periodic worker --loglevel=info
volumes:
  db:
    driver: local