"""TaskStatus added to Tasks table

Revision ID: eb9cb56ece4c
Revises: 04283d50b1e1
Create Date: 2025-07-28 16:57:16.621476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb9cb56ece4c'
down_revision: Union[str, Sequence[str], None] = '04283d50b1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#наш enum
taskstatus_enum = postgresql.ENUM('pending', 'active', 'finished', name='taskstatus')
def upgrade() -> None:
    """Upgrade schema."""
    taskstatus_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('pending', 'active', 'finished', name='taskstatus'), server_default=sa.text("'pending'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
    taskstatus_enum.drop(op.get_bind(), checkfirst=True)
